# Generated by Django 5.2.4 on 2025-07-05 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('mission', models.IntegerField()),
                ('punkte', models.IntegerField()),
                ('loesung', models.TextField()),
            ],
            options={
                'unique_together': {('level', 'mission')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='normal', max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('scrolls', models.JSONField(default=list)),
                ('completed_missions', models.ManyToManyField(blank=True, to='game.mission')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
